version: '3.8'

services:
  haos-bot:
    image: python:3.12-slim
    container_name: haos-bot-main
    env_file:
      - .env
    ports:
      - "8024:8024"
    volumes:
      - .:/app
      - ./html:/html
      - ./www:/www
      - ./logs:/logs
    working_dir: /app
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8024"
    restart: unless-stopped
    networks:
      - haos-network

  nginx:
    image: nginx:latest
    container_name: haos-bot-nginx
    ports:
      - "8033:8033"
    volumes:
      - nginx-cache:/var/cache/nginx
      - .:/app
      - ./html:/html
      - ./www:/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/app/logs
    depends_on:
      - haos-bot
    networks:
      - haos-network

networks:
  haos-network:
    driver: bridge

volumes:
  nginx-cache:

