services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./logs:/app/logs
      - ./data.json:/app/data.json
      - ./html:/app/html
    ports:
      - "8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "8000:8000"
    depends_on:
      - main
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge